image: node:14.17.0

pipelines:

  branches:
    experimental:               # Exp deploy
      - step:
         name: EXP Deploy KC LMS
         caches:
           - node
         script:
           - mv package-bitbucket.json package.json
           - mv js/overrideConfig-format.json js/overrideConfig.json
           - sed -i "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/"  js/overrideConfig.json
           - tail -n +2 .gitignore > tmp_gitignore &&  mv tmp_gitignore .gitignore
           - npm install
           - npm update
           - npm install -g gulp
           - npm install -D
           - gulp sprite
           - gulp css-build


           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E1SOWAV45IBTZX'
               PATHS: /admin/*



    stage:
      - step:                        # Stage deploy
         name: Stage Deploy KC LMS
         caches:
           - node
         script:
           - mv package-bitbucket.json package.json
           - mv js/overrideConfig-format-stage.json js/overrideConfig.json
           - sed -i "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/"  js/overrideConfig.json
           - tail -n +2 .gitignore > tmp_gitignore &&  mv tmp_gitignore .gitignore
           - npm install
           - npm update
           - npm install -g gulp
           - npm install -D
           - gulp sprite
           - gulp css-build

           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STAGE'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E2UVL8L1YNWIOM'
               PATHS: /admin/*



  custom:
    deployment-to-Stable-Manual: # Another display name
    - step:                        # Prod deploy
       name: Deploy STABLE KC LMS MANUALY
       deployment: stable
       caches:
         - node
       script:

         - mv package-bitbucket.json package.json
         - mv js/overrideConfig-format-prod.json js/overrideConfig.json
         - sed -i "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/"  js/overrideConfig.json
         - tail -n +2 .gitignore > tmp_gitignore &&  mv tmp_gitignore .gitignore
         - npm install
         - npm update
         - npm install -g gulp
         - npm install -D
         - gulp sprite
         - gulp css-build

         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STABLE'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'

         - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
           variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             AWS_DEFAULT_REGION: us-west-2
             DISTRIBUTION_ID: 'E3GJJSNYELJ4SX'
             PATHS: /quiz/*



    deployment-test-DEVOPS-12: # Another display name
    - step:                        # DEVOPS-12 deploy
       name: Deploy DEVOPS-12 KC LMS MANUALY
       deployment: DEVOPS-12
       caches:
         - node
       script:
         - mv package-bitbucket.json package.json
         - mv js/overrideConfig-format.json js/overrideConfig.json
         - sed -i "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/"  js/overrideConfig.json
         - tail -n +2 .gitignore > tmp_gitignore &&  mv tmp_gitignore .gitignore
         - npm install
         - npm update
         - npm install -g gulp
         - npm install -D
         - gulp sprite
         - gulp css-build

         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'
             PATHS: /admin/*
