#image: node:14.17.0

pipelines:

  branches:
    experimental:               # Exp deploy
      - step:
         name: EXP Deploy TNA
         script:
           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'


    stage:
      - step:                        # Stage deploy
         name: Stage Deploy TNA
         script:

           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STAGE'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'

  custom:
    deployment-to-Stable-Manual: # Another display name
    - step:                        # Prod deploy
       name: Deploy STABLE TNA MANUALY
       deployment: stable
       script:

         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STABLE'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'


    deployment-test-DEVOPS-12: # Another display name
    - step:                        # DEVOPS-12 deploy
       name: Deploy DEVOPS-12 TNA MANUALY
       deployment: DEVOPS-12

       script:
         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'
