image: node:14.17.0

pipelines:

  branches:
    experimental:               # Exp deploy
      - step:
         name: EXP Deploy KC Portals
         caches:
           - node
         script:
           - mv package.json package.json-deploybot
           - mv package.json-bitbucket package.json
           - rm package-lock.json

           - echo $hardCodedOverrideConfig > js/overrideConfig.json
           - sed -i "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/"  js/overrideConfig.json

           - npm install
           - npm update
           - npm install -g gulp
           - gulp --gulpfile gulpfile-bitbucket.js build


           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E1SOWAV45IBTZX'



    stage:
      - step:                        # Stage deploy
         name: Stage Deploy KC Portals
         caches:
           - node
         script:
           - mv package.json package.json-deploybot
           - mv package.json-bitbucket package.json
           - rm package-lock.json
           - npm install
           - npm update
           - npm install -g gulp
           - gulp --gulpfile gulpfile-bitbucket.js build

           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STAGE'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
               EXTRA_ARGS: '--exclude-from=.gitignore'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E2UVL8L1YNWIOM'



  custom:
    deployment-to-Stable-Manual: # Another display name
    - step:                        # Prod deploy
       name: Deploy STABLE KC Portals MANUALY
       deployment: stable
       caches:
         - node
       script:
         - mv package.json package.json-deploybot
         - mv package.json-bitbucket package.json
         - rm package-lock.json
         - npm install
         - npm update
         - npm install -g gulp
         - gulp --gulpfile gulpfile-bitbucket.js build

         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_STABLE'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'

         - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
           variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             AWS_DEFAULT_REGION: us-west-2
             DISTRIBUTION_ID: 'E3GJJSNYELJ4SX'



    deployment-test-DEVOPS-12: # Another display name
    - step:                        # DEVOPS-12 deploy
       name: Deploy DEVOPS-12 KC Portals MANUALY
       deployment: DEVOPS-12
       caches:
         - node
       script:
         - mv package.json package.json-deploybot
         - mv package.json-bitbucket package.json
         - rm package-lock.json
         - npm install
         - npm update
         - npm install -g gulp
         - gulp --gulpfile gulpfile-bitbucket.js build

         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH_EXP'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
             EXTRA_ARGS: '--exclude-from=.gitignore'
